### ISSUE TITLE
Unable to build provider

### ISSUE THREAD

**Issue by mdolian** [skyscrapr/terraform-provider-cloudability#11]
ETG-mdolian:terraform-provider-cloudability t15kiud$ go build
go: github.com/skyscrapr/cloudability-sdk-go@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000

The binary in the repository seems to be really old and the modules error out with it.

**Comment by skyscrapr** [comment]
Released a new version of the sdk and update the go.mod file. 
Issue should be resolved. 
Please try again.

**Comment by skyscrapr** [comment]
@mdolian  I'll leave this open till you confirm

**Comment by skyscrapr** [comment]
@mdolian build has succeeded so I'll close this. Please re-open if you need.
