### ISSUE TITLE
Terraform 0.13 Usage Instructions

### ISSUE THREAD

**Issue by petewilcock** [skyscrapr/terraform-provider-cloudability#13]
You don't appear to be on the official third party provider list as stated - can't seem to terraform init using 0.13.5:

````
terraform {
  required_providers {
    cloudability = {
      source = "github.com/skyscrapr/cloudability"
    }
  }
}
````

Not sure if this is the correct format (tried many types) but I also note you're not listed at https://registry.terraform.io/browse/providers?tier=community

Any advice?

**Comment by skyscrapr** [comment]
Hi there 

This provider is listed on the community provider list here:

https://www.terraform.io/docs/providers/type/community-index.html


I have not been doing much on the provider recently. 

I will take a look on the new requirements to be added to the registry and see if it's an easy fix. 

I'll take a quick look to see if that's the reason it no longer installs automatically.

**Comment by skyscrapr** [comment]
Looks like there is some minor documentation changes needed and I can publish the provider in the registry. I'll see if I can get it done today or tomorrow.

**Comment by petewilcock** [comment]
That would be great, thanks :)

**Comment by petewilcock** [comment]
Appreciate you're busy but if you can push the update to appear in the community list that would be very helpful. Thanks!

**Comment by skyscrapr** [comment]
I'm working on this. Will get it done over the weekend.

**Comment by skyscrapr** [comment]
This is now complete. Take a look and let me know if anything else needs to be done by opening another issue. Cheers

**Comment by skyscrapr** [comment]
Just wondering if the sample modules i've created are useful. If they can you please raise an issue and I'll update them to be published in the registry as well.
