### ISSUE TITLE
Implement configurable timeouts

### ISSUE THREAD

**Issue by irasnyd** [skyscrapr/terraform-provider-cloudability#20]
Doc: https://developer.hashicorp.com/terraform/plugin/sdkv2/resources/retries-and-customizable-timeouts

I tried to use some code like this and got an error:

```terraform
resource "cloudability_master_account" "root_account" {
  vendor_account_id = data.aws_caller_identity.current.account_id

  bucket_name   = aws_cur_report_definition.apptio.s3_bucket
  report_prefix = aws_cur_report_definition.apptio.s3_prefix
  report_name   = aws_cur_report_definition.apptio.report_name

  timeouts {
    create = "5m"
  }
}
```

Error message:

```
╷
│ Error: Unsupported block type
│ 
│   on cloudability.tf line 31, in resource "cloudability_master_account" "root_account":
│   31:   timeouts {
│ 
│ Blocks of type "timeouts" are not expected here.
╵
```

I was testing a workaround to a timeout error:

```
cloudability_master_account.root_account: Creating...
cloudability_master_account.root_account: Still creating... [10s elapsed]
╷
│ Error: Post "https://api.cloudability.com/v3/vendors/aws/accounts": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
│ 
│   with cloudability_master_account.root_account,
│   on cloudability.tf line 24, in resource "cloudability_master_account" "root_account":
│   24: resource "cloudability_master_account" "root_account" {
│ 
╵
```

**Comment by skyscrapr** [comment]
Give me a day to look into this.

**Comment by irasnyd** [comment]
Thank you! 😃 

I think this may give us a starting point:
https://github.com/skyscrapr/terraform-provider-cloudability/compare/master...irasnyd:terraform-provider-cloudability:configurable-timeout

**Comment by skyscrapr** [comment]
Hi. Can you confirm exactly what you are seeing? Is the terraform apply failing due to this timeout? Does it eventually succeed on subsequent tries? Are you sure you have access to the cloudability endpoint?

**Comment by skyscrapr** [comment]
@irasnyd sorry to chase up, but I've looked into this issue and if I'm understanding this correctly, the http client waits indefinitely for a response. That means the server is sending the timeout response. To resolve this requires a retry function over simply setting the timeout in the client. I cannot replicate the issue either so I'm just wondering in exactly what scenario you see this issue. A set of steps to repro would be great, even if it doesn't trigger the timeout.

**Comment by irasnyd** [comment]
Hi @skyscrapr,

The error message I received from Terraform is:

```
cloudability_master_account.root_account: Creating...
cloudability_master_account.root_account: Still creating... [10s elapsed]
╷
│ Error: Post "https://api.cloudability.com/v3/vendors/aws/accounts": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
│ 
│   with cloudability_master_account.root_account,
│   on cloudability.tf line 24, in resource "cloudability_master_account" "root_account":
│   24: resource "cloudability_master_account" "root_account" {
│ 
╵
```

Where my `cloudability.tf` looks like this:

```terraform
resource "aws_cur_report_definition" "apptio" {
  report_name                = "cost_usage_report_apptio"
  time_unit                  = "HOURLY"
  format                     = "textORcsv"
  compression                = "GZIP"
  s3_bucket                  = module.primary_cur.bucket.id
  s3_region                  = module.primary_cur.bucket.region
  s3_prefix                  = "cost_usage_report/apptio"
  additional_artifacts       = []
  additional_schema_elements = ["RESOURCES"]
  report_versioning          = "CREATE_NEW_REPORT"
  refresh_closed_reports     = true
}

resource "cloudability_master_account" "root_account" {
    vendor_account_id = data.aws_caller_identity.current.account_id
    bucket_name = aws_cur_report_definition.s3_bucket
    report_name = aws_cur_report_definition.report_name
    report_prefix = aws_cur_report_definition.s3_prefix
}
```

The CUR report was created many days ago and is already populated with data.

The creation of `resource "cloudability_master_account" "root_account" { ... }` times out, and produces the error message:

```
cloudability_master_account.root_account: Creating...
cloudability_master_account.root_account: Still creating... [10s elapsed]
╷
│ Error: Post "https://api.cloudability.com/v3/vendors/aws/accounts": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
│ 
│   with cloudability_master_account.root_account,
│   on cloudability.tf line 24, in resource "cloudability_master_account" "root_account":
│   24: resource "cloudability_master_account" "root_account" {
│ 
╵
```

Note that the timeout _always_ happens in approx 10s, as shown in the error message. I am sure there is a default timeout of 10s being set somehow.

I wrote a simple Python script to make the same API calls to Cloudability. I used this script to verify that my Cloudability API key is configured and working correctly. When I made the same API call used by the `cloudability_master_account` resource, I noticed that it takes 60-120 seconds to complete and return. I have a very large AWS Organization; it takes a LONG time for Cloudability to scan it and return a result.

I don't have much more information to provide. I have verified that the Cloudability APIs work correctly, and that I have a working API key. This provider seems to always hit a timeout.

**Comment by skyscrapr** [comment]
ok, found the issue. I've hardcoded :-( the timeout in the cloudability go sdk here: https://github.com/skyscrapr/cloudability-sdk-go/blob/master/cloudability/client.go#L34
I'll extend the default timeout to 30s and also make the timeout configurable as per your PR.  

Give me another day to resolve.

**Comment by skyscrapr** [comment]
Ok. I've actually released a new version that should resolve this issue for you.  Timeouts are now supported in this format. An example of usage is here:

https://github.com/skyscrapr/terraform-cloudability-modules/blob/master/cloudability-master-account/main.tf

Can you please confirm this works for you and I'll close the issue and update the docs. 

Thanks

R
