### ISSUE TITLE
400 Bad Request When using View Resource

### ISSUE THREAD

**Issue by aafishman** [skyscrapr/terraform-provider-cloudability#22]
Thanks for working on this! Been helpful as we start to set up config for our instance. 

I've had trouble getting the views resource to work. Even with as simple an example as I could make (from your docs only the title should be required? https://registry.terraform.io/providers/skyscrapr/cloudability/latest/docs/resources/view#title)

Is it possible to import a view? Could reverse-engineer it that way as well

```
resource "cloudability_view" "Azure_test" {
  title = "Azure"
}
```
gets me a  `Error: {"error":{"status":400,"code":"request_validation_failed","messages":["Bad Request"],...`

Thanks!

**Comment by aafishman** [comment]
after trying some in the console, and importing (looks like you already got that working, just needed to know the view ID - which I grabbed via API) I was able to get this to work:

**Comment by skyscrapr** [comment]
Thanks for raising the issue. 
Looks like this requires a change to the schema to require the filter. Let me run some tests and I will update the docs.  

Importing is supported and should work however I will double check with a test as well. 

Give me 2-3 days to update. 

Cheers

Richard

**Comment by aafishman** [comment]
Thanks, appreciate the response 👍

**Comment by skyscrapr** [comment]
Looks like Cloudability has changed the behaviour of the API. 

This needs a bit more work to resolve the business mappings resource issues. 

I'm working on it and should have a fix in a day or so.

**Comment by skyscrapr** [comment]
I've done some initial testing and it appears to be mostly schema changes required. I've updated the samples here: https://github.com/skyscrapr/terraform-cloudability-modules/tree/master/cloudability-business-mappings. Please take a look and if this works for you, I'll update the scheme to ensure the correct attributes are required.

**Comment by aafishman** [comment]
Yep 👍 ! Verified that I can create a mapping and grab it via ID as in the example above to create a view that references it! Thank you!

**Comment by skyscrapr** [comment]
Ok. Thanks for verifying. I'll release a new version with the schema fixes and I'll close the issue when released.

**Comment by antonym** [comment]
Just checking in on the schema fixes, I was trying to import some existing views from Cloudability into the Terraform state and it appears that the filter was empty in the imported resource state when there are filters set.

Are these the schema fixes you were talking about? Thanks!

**Comment by skyscrapr** [comment]
I haven't had a chance to test this change yet. Let me take a look at this today and see if I can generate a PR to resolve. 

Thanks for bumping this.

**Comment by skyscrapr** [comment]
I can see the issue you are having and how to resolve it. @antonym, can you please raise a ticket with Cloudability as I need someone to give me access to a test environment to test the changes.

**Comment by antonym** [comment]
Thanks, I raised a ticket with Cloudability and will let you know what I hear back.

**Comment by antonym** [comment]
Hey @skyscrapr, Apptio has agreed to get a test account set up for two weeks and extend if needed so that we can continue to debug the changes. Do you have an e-mail I can contact you with and we can get all of those details sorted out?

**Comment by skyscrapr** [comment]
Nice going. email: github@skyscrapr.io

**Comment by antonym** [comment]
Got it, thanks!

**Comment by skyscrapr** [comment]
I've updated the view resource to resolve the issues. Import will now also work correctly. 
I've also added views and view data sources that can be used to query all views.
Please take a look and see if the issues are resolved.

Re-open the issue if needed.

**Comment by skyscrapr** [comment]
@antonym Note you will need to upgrade the provider to the latest version v0.0.24

**Comment by antonym** [comment]
Thanks for your work on this, the plan seemed to work but when I went to apply, it appears the plugin crashed:

```
Stack trace from the terraform-provider-cloudability_v0.0.24 plugin:

panic: interface conversion: interface {} is []interface {}, not []string

goroutine 44 [running]:
github.com/skyscrapr/terraform-provider-cloudability/cloudability.resourceViewCreate(0x0?, {0xc1ce80?, 0xc00038cb40})
github.com/skyscrapr/terraform-provider-cloudability/cloudability/resource_view.go:76 +0x63a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xd66800?, {0xd66800?, 0xc000432900?}, 0xd?, {0xc1ce80?, 0xc00038cb40?})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0000d56c0, {0xd66800, 0xc000432900}, 0xc00071b6c0, 0xc000555500, {0xc1ce80, 0xc00038cb40})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0004afda0, {0xd66800?, 0xc0004327e0?}, 0xc00023d400)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00023ac80, {0xd66800?, 0xc0005a1da0?}, 0xc0001a08c0)
github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xc0b720?, 0xc00023ac80}, {0xd66800, 0xc0005a1da0}, 0xc0001a0850, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002361e0, {0xd6a320, 0xc0004d44e0}, 0xc0007306c0, 0xc0004beae0, 0x1200d20, 0x0)
google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0002361e0, {0xd6a320, 0xc0004d44e0}, 0xc0007306c0, 0x0)
google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-cloudability_v0.0.24 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by antonym** [comment]
No problem, I tested 0.0.27 and it appears to have successfully applied now!  Thanks again for your assistance on this!
