### ISSUE TITLE
Import existing business mappings into Terraform state file

### ISSUE THREAD

**Issue by prabha11-sys** [skyscrapr/terraform-provider-cloudability#23]
Hello,
Thanks for sharing this provider. As I already have many business mappings created in cloudability, I was wondering if there is a way to import everything into terraform and start managing them from terraform in the future. I dont want to delete the business mappings and recreate them in terraform to get these into the state file. Any ideas ?

**Comment by skyscrapr** [comment]
Yes. This is possible. Import support is already built into the resource. However. I haven't tested this. Give me a day to look into this and I'll update the docs.

**Comment by skyscrapr** [comment]
Hi @prabha11-sys, importing business mappings does work. The default importer is implemented. This means you can import by business mapping id. The command to do this would be:
`terraform import cloudability_business_mapping.[resource_name] [business_mapping_id]`

The easiest way to get the business mapping id is to run this command from a shell:
`curl https://api.cloudability.com/v3/business-mappings/dimensions \\
     -u '[auth_token]:'`
For more information, take a look at the [documentation](https://help.apptio.com/en-us/cloudability/api/v3/business_mappings_endpoint.htm)

It is possible to implement import via the actual name of the business mapping however this is some work to complete.
So hopefully this resolves your issue. If not, or if you think there is value in implementing the import by name, please open a new issue.

**Comment by skyscrapr** [comment]
@prabha11-sys I've just released a new version of the provider that handles eventual consistency for the view resource during updates. But you don't need it to support import of views.

**Comment by prabha11-sys** [comment]
Thanks @skyscrapr. I tried importing a view which is named "AWS eDEV" and I had the below error,

**terraform import "cloudability_view.AWS eDEV" "369258"** 
│
│
│ Error: Invalid character
│
│   on <import-address> line 1:
│    1: cloudability_view.AWS eDEV
│
│ Expected an attribute access or an index operator.

The problem is with the space in the view name. There is another view which I imported using the below command and it worked perfectly,
**terraform import cloudability_view.AWS 369258**
