### ISSUE TITLE
Issue while importing a view or business mapping.

### ISSUE THREAD

**Issue by prabha11-sys** [skyscrapr/terraform-provider-cloudability#24]
Thanks @skyscrapr. I tried importing a view which is named "AWS eDEV" and I had the below error,

terraform import "cloudability_view.AWS eDEV" "369258"
│
│
│ Error: Invalid character
│
│ on line 1:
│ 1: cloudability_view.AWS eDEV
│
│ Expected an attribute access or an index operator.

The problem is with the space in the view name. There is another view which I imported using the below command and it worked perfectly,
terraform import cloudability_view.AWS 369258

**Comment by skyscrapr** [comment]
Thanks for the feedback. I'll look at how to handle the space. Give me another day to look into it further.

**Comment by skyscrapr** [comment]
HI @prabha11-sys, I just took a look at this and there doesn't appear to be any issue with  the title attribute or the filters containing spaces. But it looks like terraform resource names cannot contain spaces. 

The error i receive is: `Error: Invalid resource name
│ A name must start with a letter or underscore and may contain only letters, digits, underscores, and dashes.` 

If you ensure the resource name does not contain spaces, then you should be able to import the view correctly. For example: `terraform import "cloudability_view.AWS_eDEV" "369258"` 

I cannot replicate the error you are seeing.
Are you using the latest version of terraform?

**Comment by prabha11-sys** [comment]
Hi @skyscrapr , I am using 
Terraform v1.5.2
on windows_386

See an example of another scenario where i tried importing a business mapping named "Azure Service Category"

**Command**
terraform import "cloudability_business_mapping.Azure Service Category" "3"

**Error below:**
Error: Invalid character
│
│   on <import-address> line 1:
│    1: cloudability_business_mapping.Azure Service Category
│
│ Expected an attribute access or an index operator.
╵

For information on valid syntax, see:
https://www.terraform.io/docs/cli/state/resource-addressing.html

**Comment by skyscrapr** [comment]
It is part of the HCL definition to not accept spaces in the resource name. You can see the details [here](https://developer.hashicorp.com/terraform/language/syntax/configuration#)

This does not prevent you using spaces in the title attribute. 

I suggest replacing the spaces with underscores.

Example: 
`terraform import "cloudability_business_mapping.Azure_Service_Category" "3"`

The imported resource should contain:
`title = "Azure Service Category"`

**Comment by skyscrapr** [comment]
@prabha11-sys I'm closing this issue since the resource naming restrictions are documented. If you think this issue is not resolved, please re-open.
