### ISSUE TITLE
Is there a way to import all business mappings or views at once ?

### ISSUE THREAD

**Issue by prabha11-sys** [skyscrapr/terraform-provider-cloudability#26]
Hi @skyscrapr 
Is there a way to import all business mappings or views at once ? I have numerous views/ business mappings that were created in cloudability and I am looking for a easier way to import and update the terraform state file without having to run "terraform import" for each view or business mapping.

Additionally, after each import of a view or business mapping, I need to reformat the contents and update my .tf file with the imported contents(in the state file) which is a time-consuming task. For instance, once I imported a business mapping, the state file would have this,

{
"version": 4,
  "terraform_version": "1.5.2",
  "serial": 31,
  "lineage": "89455dbb-bc79-b1b1-9f22-2ae180c3c0b4",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "cloudability_business_mapping",
      "name": "AWS_Payer_AccountID",
      "provider": "provider[\"registry.terraform.io/skyscrapr/cloudability\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "default_value": "AWS_DEV",
            "id": "5",
            "index": 5,
            "kind": "BUSINESS_DIMENSION",
            "name": "AWS_Payer_AccountID",
            "statement": [
              {
                "match_expression": "DIMENSION['account_identifier'] == 'xxx-xxx-xxx'",
                "value_expression": "'AWS_PROD'"
              },
              {
                "match_expression": "DIMENSION['account_identifier'] == 'yyy-yyy-yyy'",
                "value_expression": "'AWS_DEV'"
              }
            ],
            "timeouts": null,
            "updated_at": "2023-07-06T21:00:45.072Z"
          },
          "sensitive_attributes": [],
          "private": "eyJlMmJmYjczMC1lY2FhLTExZTYtOGY4OC0zNDM2M2JjN2M0YzAiOnsiY3JlYXRlIjo2MDAwMDAwMDAwMCwiZGVsZXRlIjo2MDAwMDAwMDAwMCwicmVhZCI6NjAwMDAwMDAwMDAsInVwZGF0ZSI6NjAwMDAwMDAwMDB9LCJzY2hlbWFfdmVyc2lvbiI6IjAifQ=="
        }
      ]
    },

From this, I have to update my .tf file by reformatting into this,

resource "cloudability_business_mapping" "AWS_Payer_AccountID" {
  name = "AWS_Payer_AccountID"
    default_value = "AWS_DEV"
    kind = "BUSINESS_DIMENSION"
    statement {
             match_expression = "DIMENSION['account_identifier'] == 'xxx-xxx-xxx'"
             value_expression = "'AWS_PROD'"
              }
    statement {
             match_expression = "DIMENSION['account_identifier'] == 'yyy-yyy-yyy'"
             value_expression = "'AWS_DEV'"
    }
}

**Comment by skyscrapr** [comment]
You are in luck. 

 There is a brand new feature called "import blocks" that allows multiple resources to be imported. Take a look at the docs [here](https://developer.hashicorp.com/terraform/language/import). You still need to pre-define all the resources in your terraform and also define the import block to map the resources to the config. 

This is a new feature of terraform 1.5.0 and not a provider-related feature.
