### ISSUE TITLE
Support for Business metric

### ISSUE THREAD

**Issue by prabha11-sys** [skyscrapr/terraform-provider-cloudability#32]
Hi @skyscrapr , this is not an issue but a question.
Does the cloudability provider support the management of business metric ? Would be helpful if that feature is supported.

**Comment by skyscrapr** [comment]
Technically this may be supported. 
It's just a string in the `kind` attribute. 

Check the docs [here](https://registry.terraform.io/providers/skyscrapr/cloudability/latest/docs/resources/business_mapping) 

I haven't tested it though. So there are no tests to validate this. 

Might be worth giving it a try
`kind = BUSINESS_METRIC`

Unsure what the parameters are for a metric over a dimension.

**Comment by skyscrapr** [comment]
It looks like METRICS have additional attributes. So my guess is this needs work to be supported. 

Best to raise a ticket with apptio. 

Happy to do the work. But time is hard to find.

**Comment by skyscrapr** [comment]
This is a pretty easy fix. But the easiest way to implement this is to create a new resource called `business_metric`

I will test it tomorrow.
