### ISSUE TITLE
Business metric cannot be updated

### ISSUE THREAD

**Issue by prabha11-sys** [skyscrapr/terraform-provider-cloudability#35]
Hello @skyscrapr 
I get the below error while updating a business metric through terraform,

cloudability_business_metric.RI_Quantity_Needed: Modifying... [id=2]
╷
│ Error: doesn't support update
│
│   with cloudability_business_metric.RI_Quantity_Needed,
│   on business_metric.tf line 31, in resource "cloudability_business_metric" "RI_Quantity_Needed":
│   31: resource "cloudability_business_metric" "RI_Quantity_Needed" {

Below is my resource in terraform config

resource "cloudability_business_metric" "RI_Quantity_Needed" {
  default_value            = "0"
  default_value_expression = null
  name                     = "RI Quantity Needed"
  number_format            = "number"
  pre_match_expression     = null
  statement {
    match_expression = "DIMENSION['usage_type'] CONTAINS 'Virtual Machines::'"
    value_expression = "(METRIC['usage_hours'] - METRIC['reserved_hours']) / 25"
  }
}

When I change the config to the below  and run terraform apply, it works then

resource "cloudability_business_metric" "RI_Quantity_Needed" {
  default_value_expression            = "0"
  /*default_value_expression = null*/
  name                     = "RI Quantity Needed"
  number_format            = "number"
  pre_match_expression     = null
  statement {
    match_expression = "DIMENSION['usage_type'] CONTAINS 'Virtual Machines::'"
    value_expression = "(METRIC['usage_hours'] - METRIC['reserved_hours']) / 25"
  }
}

see output of terraform apply,

cloudability_business_metric.RI_Quantity_Needed: Destroying... [id=2]
cloudability_business_metric.RI_Quantity_Needed: Destruction complete after 1s
cloudability_business_metric.RI_Quantity_Needed: Creating...
cloudability_business_metric.RI_Quantity_Needed: Creation complete after 1s [id=2]

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.

**Comment by prabha11-sys** [comment]
After the resource RI_Quantity_Needed is updated by the terraform apply command, running a terraform plan still shows the below instead of "infrastructure is up to date"

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # cloudability_business_metric.RI_Quantity_Needed must be replaced
-/+ resource "cloudability_business_metric" "RI_Quantity_Needed" {
      - default_value            = "0" -> null # forces replacement
      ~ id                       = "2" -> (known after apply)
      ~ index                    = 2 -> (known after apply)
        name                     = "RI Quantity Needed"
      ~ updated_at               = "2023-08-04T04:29:46.886Z" -> (known after apply)
        # (2 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

**Comment by skyscrapr** [comment]
Hi @prabha11-sys. When I created the resource I wondered if the way apptio handles the default value might be an issue. 

I'll raise this with apptio. 
It would be great if you could also raise a ticket. 

I'll feedback on Monday.

**Comment by skyscrapr** [comment]
fixed in v0.0.34
